### ISSUE TITLE
[Feature request] Add support for Thunderbird 78

### ISSUE THREAD

**Issue by mohegan** [balbusm/xul-ext-eds-calendar#34]
Can you add support for Thunderbird 78, please ?

**Comment by sciancio** [comment]
+1

**Comment by jacobzimmermann** [comment]
+1

**Comment by XSimicz** [comment]
+1

**Comment by AJJLagerweij** [comment]
I'm not a programmer but if required I would like to help you out in the testing. I, and so I expect the others here, are aware that the incompatibility is not the fault of any of the devs. But since Ubuntu 20.04 LTS updated me to Thunderbird 78 this extension is one of the pieces that I am missing. I loved using this on previous versions of Thunderbird. 
Hence, I hope to help out if possible, sadly my knowledge does not extend anywhere further than python for scientific use...
But please tell me if there is any help I can provide.

**Comment by balbusm** [comment]
See Beta version for TB78+
https://github.com/balbusm/xul-ext-eds-calendar/releases/tag/0.9.0-beta1

Let me know if you see any issues

General remarks regarding this addon:
- It uses C++ libs under the hood to communicate with Gnome Notifications
- Thunderbird devs are pushing towards disabling C++ usage (security reasons)
To make it work in TB78 I had to switch addon to Experiments API (privileged mode), which is fine at the moment, but at some point addons utilizing Experiments API will be disabled on Thunderbird Addons Page.
When they disable Experiments API there are two possible scenarios:
- it won't be possible to publish updates on Thunderbird Addons Page, but fixes will be possible - only manual updates via Github
- it won't be possible to apply fix - then it's over

**Comment by AJJLagerweij** [comment]
Thanks for the update, everything seems to be working fine. The terminal log spits out many:
```shell 
console.log: "[edscalendar] Collection2.length %d itemNumber %d" 10 2
```
where the numbers at the end are changing, and the events appear in the Gnome Calender. Great.

This did add quite a lot of time to the startup of thunderbird, over 30sec. I assume that this is because I've lots of events. This situation is workable though.

Regarding the API changes, I am a bit surprised that they want to drop C++ totally from the add-ons. I do understand their motivation however.
Would it be possible to brainstorm regarding a possible solution after this type of extension is not possible at all.
Currently I can only think of one thing, moving your calendar to an **online service provider** that is supported by both Thunderbird and gnome online accounts. This way both Thunderbird and Gnome communicate with the server, and the events will be available in both applications and thus in the Gnome Date and Time as well.
Clearly this is not ideal, as you'll have to go through external servers, which sounds really inefficient and which you might not want to because of privacy concerns.

**Comment by balbusm** [comment]
@AJJLagerweij  could you verify new release with improved startup time.

https://github.com/balbusm/xul-ext-eds-calendar/releases/tag/0.9.0-rc1

Regarding C++ libs.
They actually cut off addons from C++ in Firefox (TB share codebase).
Current state for FF is that Experiments API is enabled, however you cannot publish such an addon on FF web page.

I see two solutions. Use local server to populate Gnome Calendar or use [native messaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) (addon can call external app). Both solutions are basically the same, they are using bridge between external world and addon.  The problem with that idea is that 3rd party application has to be installed manually. 
On the bright side  TB development is couple years behind FF, so problem shouldn't come up anytime soon.

**Comment by PoisonFrog** [comment]
I downloaded the new version and its working. If I find any bugs I will report here. Thanks for releasing a new version for Thunderbird 78.

**Comment by balbusm** [comment]
Version 0.9.0 released. 
Closing ticket.
